# 服务端口
server:
  port: 9000
  http:
    # 字符集过滤器
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: Idempotent
  redis:
    #redis服务器地址
    host: 47.111.235.127
    port: ***
    password: ***
    database: 2
    timeout: 6000
    ## 连接池中的最大连接数
    poolMaxTotal: 10
    ## 连接池中的最大空闲连接
    poolMaxIdle: 10
    ## 连接池最大阻塞等待时间（使用负值表示没有限制）
    poolMaxWait: 3000

## 项目配置
project:
  # 1-UUID; 2-Remote接口
  type: 2
  # type: 2 -> Remote接口 HTTP请求
  url: http://47.111.235.127:8090/api/get/unique-record-segment-test


